# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1685865a4f77cfa8b5f5c5ddc61275d451ba92a0dbd5cd6e967011f100987bb6d8c1b9c583fc1f6809b2572ecbcdccbb47dac3a335a2bcb376e139b748895a03

test:
  secret_key_base: 7f96d44ac343ffa7eb4bae6e69bd902b16ed91967217d297713b0c229a53a5ab1c767917b336ebbb014c19cfc3f8897719d7dd99bd325579f5c61813e181e21b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
